'use strict'

module.exports = {

  USER_NUMBER_LENGTH: 6,

  USER_GENDER_MALE: 1,
  USER_GENDER_FEMALE: 2,

  USER_NICKNAME_MIN_LENGTH: 2,
  USER_NICKNAME_MAX_LENGTH: 20,

  USER_PASSWORD_MIN_LENGTH: 6,
  USER_PASSWORD_MAX_LENGTH: 20,

  USER_DOMAIN_MIN_LENGTH: 5,
  USER_DOMAIN_MAX_LENGTH: 20,

  INVITE_CODE_MAX_COUNT_PER_USER: 10,
  INVITE_CODE_MAX_AGE_BY_MONTH: 6,

  CAREER_COMPANY_MAX_LENGTH: 20,
  CAREER_JOB_MAX_LENGTH: 20,
  CAREER_DESCRIPTION_MAX_LENGTH: 300,

  EDUCATION_COLLEGE_MAX_LENGTH: 20,
  EDUCATION_SPECIALITY_MAX_LENGTH: 20,
  EDUCATION_DESCRIPTION_MAX_LENGTH: 300,
  EDUCATION_DEGREE_VALUES: [
    '本科',
    '硕士',
    '博士',
    '其他'
  ]

}

